# Generated by Django 5.0.2 on 2024-03-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "poster",
                    models.FileField(
                        default="posters/default.jpg", upload_to="posters/"
                    ),
                ),
                (
                    "trailer",
                    models.CharField(
                        default="https://www.youtube.com/watch?v=5PSNL1qE6VY",
                        max_length=100,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Hindi", "Hindi"),
                            ("Tamil", "Tamil"),
                            ("Telugu", "Telugu"),
                            ("Malayalam", "Malayalam"),
                            ("Kannada", "Kannada"),
                            ("Bengali", "Bengali"),
                            ("Marathi", "Marathi"),
                        ],
                        max_length=100,
                    ),
                ),
                ("link", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.movie"
                    ),
                ),
            ],
            options={
                "ordering": ["created_on"],
            },
        ),
    ]
