# Generated by Django 5.0.2 on 2024-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="logo",
            field=models.FileField(default="logos/default.jpg", upload_to="logos/"),
        ),
    ]
