# Generated by Django 5.0.2 on 2024-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_movie_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="logo",
            field=models.FileField(
                default="media/1623408-t-9ec4d70dcf2b.webp", upload_to="logos/"
            ),
        ),
    ]
