# Generated by Django 5.0.2 on 2024-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_movie_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_file",
            field=models.FileField(default="movies/default.mp4", upload_to="movies/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Adventure", "Adventure"),
                    ("Comedy", "Comedy"),
                    ("Crime", "Crime"),
                    ("Drama", "Drama"),
                    ("Fantasy", "Fantasy"),
                    ("Historical", "Historical"),
                    ("Horror", "Horror"),
                    ("Mystery", "Mystery"),
                    ("Romance", "Romance"),
                    ("Science Fiction", "Science Fiction"),
                    ("Thriller", "Thriller"),
                    ("Western", "Western"),
                ],
                default="Action",
                max_length=100,
            ),
        ),
    ]
