# Generated by Django 5.0.2 on 2024-04-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_movie_duration_movie_movie_file_alter_movie_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_rating",
            field=models.CharField(
                choices=[
                    ("G", "G"),
                    ("PG", "PG"),
                    ("PG-13", "PG-13"),
                    ("R", "R"),
                    ("U", "U"),
                    ("UA", "UA"),
                    ("A", "A"),
                    ("S", "S"),
                    ("U/A", "U/A"),
                    ("A/A", "A/A"),
                ],
                default="U",
                max_length=100,
            ),
        ),
    ]
