# Generated by Django 5.0.2 on 2024-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_movie_rating_movie_movie_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="trailer",
            field=models.FileField(
                default="trailers/default.mp4", upload_to="trailers/"
            ),
        ),
    ]
