# Generated by Django 5.0.6 on 2024-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_remove_movie_movie_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', max_length=100),
        ),
    ]
